/* .mtz package builder.
 *
 * An .mtz is a zip archive. Loose asset folders (wallpaper/, fonts/, ringtones/,
 * boots/, preview/) live directly in the archive; UI modules (framework-res,
 * com.android.systemui, …) are *nested zips stored without compression*, each
 * containing a theme_values.xml.
 */
(function () {
  'use strict';

  const U = window.Util;
  const ICON_CANVAS = 192;

  /* ---------- XML generation ---------- */

  function descriptionXml(state) {
    const v = state.values;
    return `<?xml version="1.0" encoding="UTF-8"?>
<MIUI-Theme>
    <Title>${U.xmlEscape(v.title || 'Untitled theme')}</Title>
    <Designer>${U.xmlEscape(v.designer || '')}</Designer>
    <Author>${U.xmlEscape(v.author || '')}</Author>
    <Version>${U.xmlEscape(v.version || '1.0')}</Version>
    <UIVersion>${U.xmlEscape(v.uiVersion || '13')}</UIVersion>
    <Description>${U.xmlEscape(v.description || '')}</Description>
    <Platform>Android</Platform>
    <GeneratedBy>Android Theme Studio</GeneratedBy>
</MIUI-Theme>
`;
  }

  function formatValue(kind, value) {
    switch (kind) {
      case 'color': return U.normalizeColor(value) || '#FF000000';
      case 'dimen': {
        const n = String(value).trim();
        return /^[0-9.]+$/.test(n) ? `${n}.0dip`.replace('.0.0', '.0') : n;
      }
      case 'bool': return value === true || value === 'true' ? 'true' : 'false';
      case 'integer': return String(parseInt(value, 10) || 0);
      default: return String(value);
    }
  }

  /* Collect theme_values entries for one module: schema-mapped fields first,
     then custom entries (which override same-name built-ins). */
  function moduleEntries(state, def, module) {
    const map = new Map();
    for (const field of window.Platforms.fields(def)) {
      const t = field.target;
      if (!t || t.module !== module) continue;
      const value = state.values[field.key];
      if (value === undefined || value === null || value === '') continue;
      map.set(t.name, { kind: t.kind || 'color', name: t.name, value });
    }
    for (const e of (state.values.customValues || [])) {
      if (e.module !== module || !e.name || !U.validXmlName(e.name)) continue;
      map.set(e.name, { kind: e.kind, name: e.name, value: e.value });
    }
    return [...map.values()];
  }

  function themeValuesXml(entries) {
    const tag = (kind) => kind === 'drawable' ? 'drawable' : kind;
    const lines = entries.map(e =>
      `    <${tag(e.kind)} name="${U.xmlEscape(e.name)}">${U.xmlEscape(formatValue(e.kind, e.value))}</${tag(e.kind)}>`);
    return `<?xml version="1.0" encoding="UTF-8"?>
<MIUI_Theme_Values>
${lines.join('\n')}
</MIUI_Theme_Values>
`;
  }

  function transformConfigXml(state) {
    const v = state.values;
    return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Android Theme Studio. Icon transform support varies across
     MIUI versions; the mask/border/pattern PNGs beside this file are the
     broadly-supported mechanism. -->
<Icon_Transform_Config>
    <UseConfig>true</UseConfig>
    <Shape>${U.xmlEscape(v.iconShape)}</Shape>
    <Scale>${(v.iconScale / 100).toFixed(2)}</Scale>
    <CornerRadiusPercent>${v.iconRadius}</CornerRadiusPercent>
    <UseBackground>${v.iconBgEnable ? 'true' : 'false'}</UseBackground>
    <BackgroundColor>${U.normalizeColor(v.iconBg)}</BackgroundColor>
    <UseBorder>${v.iconBorder ? 'true' : 'false'}</UseBorder>
    <BorderColor>${U.normalizeColor(v.iconBorderColor)}</BorderColor>
    <BorderWidth>${v.iconBorderWidth}</BorderWidth>
</Icon_Transform_Config>
`;
  }

  /* ---------- canvas rendering ---------- */

  function shapePath(ctx, size, shape, radiusPct) {
    const s = size;
    ctx.beginPath();
    switch (shape) {
      case 'circle':
        ctx.arc(s / 2, s / 2, s / 2, 0, Math.PI * 2);
        break;
      case 'squircle': {
        /* superellipse |x|^n + |y|^n = 1 with n ≈ 4 */
        const n = 4, r = s / 2;
        for (let a = 0; a <= 360; a += 2) {
          const t = a * Math.PI / 180;
          const x = r + Math.sign(Math.cos(t)) * r * Math.pow(Math.abs(Math.cos(t)), 2 / n);
          const y = r + Math.sign(Math.sin(t)) * r * Math.pow(Math.abs(Math.sin(t)), 2 / n);
          a === 0 ? ctx.moveTo(x, y) : ctx.lineTo(x, y);
        }
        ctx.closePath();
        break;
      }
      case 'rounded': {
        const r = s * Math.min(50, Math.max(0, radiusPct)) / 100;
        ctx.roundRect(0, 0, s, s, r);
        break;
      }
      case 'teardrop':
        ctx.roundRect(0, 0, s, s, [s / 2, s / 2, s / 2, s * 0.16]);
        break;
      case 'hexagon': {
        const pts = [[0.5, 0], [0.93, 0.25], [0.93, 0.75], [0.5, 1], [0.07, 0.75], [0.07, 0.25]];
        pts.forEach(([x, y], i) => i === 0 ? ctx.moveTo(x * s, y * s) : ctx.lineTo(x * s, y * s));
        ctx.closePath();
        break;
      }
      default: /* original: full square mask (no clipping) */
        ctx.rect(0, 0, s, s);
    }
  }

  function canvasBytes(canvas, type, quality) {
    return new Promise((resolve, reject) => {
      canvas.toBlob(async (blob) => {
        if (!blob) return reject(new Error('Canvas export failed'));
        resolve(new Uint8Array(await blob.arrayBuffer()));
      }, type || 'image/png', quality);
    });
  }

  async function iconAssets(state) {
    const v = state.values;
    const out = {};

    /* icon_mask.png — opaque = visible area of the icon */
    const mask = document.createElement('canvas');
    mask.width = mask.height = ICON_CANVAS;
    let ctx = mask.getContext('2d');
    ctx.fillStyle = '#FFFFFF';
    shapePath(ctx, ICON_CANVAS, v.iconShape, v.iconRadius);
    ctx.fill();
    out['icon_mask.png'] = await canvasBytes(mask);

    /* icon_background.png — plate drawn behind icons */
    if (v.iconBgEnable) {
      const bg = document.createElement('canvas');
      bg.width = bg.height = ICON_CANVAS;
      ctx = bg.getContext('2d');
      if (v.iconBgGradient) {
        const rad = (v.iconBgAngle - 90) * Math.PI / 180;
        const cx = ICON_CANVAS / 2, r = ICON_CANVAS / 2;
        const grad = ctx.createLinearGradient(
          cx - Math.cos(rad) * r, cx - Math.sin(rad) * r,
          cx + Math.cos(rad) * r, cx + Math.sin(rad) * r);
        grad.addColorStop(0, U.toCss(v.iconBg));
        grad.addColorStop(1, U.toCss(v.iconBg2));
        ctx.fillStyle = grad;
      } else {
        ctx.fillStyle = U.toCss(v.iconBg);
      }
      shapePath(ctx, ICON_CANVAS, v.iconShape, v.iconRadius);
      ctx.fill();
      out['icon_background.png'] = await canvasBytes(bg);
    }

    /* icon_border.png — ring stroked along the mask edge */
    if (v.iconBorder) {
      const border = document.createElement('canvas');
      border.width = border.height = ICON_CANVAS;
      ctx = border.getContext('2d');
      ctx.strokeStyle = U.toCss(v.iconBorderColor);
      ctx.lineWidth = v.iconBorderWidth * 2;
      shapePath(ctx, ICON_CANVAS, v.iconShape, v.iconRadius);
      ctx.save();
      ctx.clip();
      ctx.stroke();
      ctx.restore();
      out['icon_border.png'] = await canvasBytes(border);
    }

    /* icon_pattern.png — gloss overlay */
    if (v.iconGloss) {
      const gloss = document.createElement('canvas');
      gloss.width = gloss.height = ICON_CANVAS;
      ctx = gloss.getContext('2d');
      const grad = ctx.createLinearGradient(0, 0, 0, ICON_CANVAS);
      grad.addColorStop(0, 'rgba(255,255,255,0.28)');
      grad.addColorStop(0.5, 'rgba(255,255,255,0.06)');
      grad.addColorStop(0.52, 'rgba(255,255,255,0)');
      grad.addColorStop(1, 'rgba(255,255,255,0)');
      ctx.fillStyle = grad;
      shapePath(ctx, ICON_CANVAS, v.iconShape, v.iconRadius);
      ctx.fill();
      out['icon_pattern.png'] = await canvasBytes(gloss);
    }

    return out;
  }

  function loadImage(dataUrl) {
    return new Promise((resolve, reject) => {
      const img = new Image();
      img.onload = () => resolve(img);
      img.onerror = () => reject(new Error('Could not decode image'));
      img.src = dataUrl;
    });
  }

  /* Draw a wallpaper onto a context: the uploaded image cover-cropped, or the
     configured gradient when none was uploaded. */
  async function drawWallpaper(ctx, state, assetKey, w, h) {
    const asset = state.assets[assetKey];
    if (asset) {
      const img = await loadImage(asset.dataUrl);
      const scale = Math.max(w / img.width, h / img.height);
      const dw = img.width * scale, dh = img.height * scale;
      ctx.drawImage(img, (w - dw) / 2, (h - dh) / 2, dw, dh);
    } else {
      const rad = ((state.values.wpGradientAngle || 160) - 90) * Math.PI / 180;
      const r = Math.hypot(w, h) / 2;
      const grad = ctx.createLinearGradient(
        w / 2 - Math.cos(rad) * r, h / 2 - Math.sin(rad) * r,
        w / 2 + Math.cos(rad) * r, h / 2 + Math.sin(rad) * r);
      grad.addColorStop(0, U.toCss(state.values.wpGradientA));
      grad.addColorStop(1, U.toCss(state.values.wpGradientB));
      ctx.fillStyle = grad;
      ctx.fillRect(0, 0, w, h);
    }
  }

  async function wallpaperBytes(state, assetKey, w, h) {
    const canvas = document.createElement('canvas');
    canvas.width = w; canvas.height = h;
    await drawWallpaper(canvas.getContext('2d'), state, assetKey, w, h);
    return canvasBytes(canvas, 'image/jpeg', 0.92);
  }

  async function previewImage(state, assetKey, label) {
    const w = 540, h = 1170;
    const canvas = document.createElement('canvas');
    canvas.width = w; canvas.height = h;
    const ctx = canvas.getContext('2d');
    await drawWallpaper(ctx, state, assetKey, w, h);
    ctx.fillStyle = 'rgba(0,0,0,0.35)';
    ctx.fillRect(0, h - 150, w, 150);
    ctx.fillStyle = U.toCss(state.values.accentColor);
    ctx.fillRect(0, h - 150, w, 6);
    ctx.fillStyle = '#FFFFFF';
    ctx.font = '600 34px system-ui, sans-serif';
    ctx.fillText(state.values.title || 'Untitled theme', 28, h - 92);
    ctx.font = '24px system-ui, sans-serif';
    ctx.fillStyle = 'rgba(255,255,255,0.8)';
    ctx.fillText(label, 28, h - 48);
    return canvasBytes(canvas, 'image/jpeg', 0.88);
  }

  /* ---------- assembly ---------- */

  function extOf(name, fallback) {
    const m = /\.([a-z0-9]+)$/i.exec(name || '');
    return m ? m[1].toLowerCase() : fallback;
  }

  async function nestedModule(outer, name, files) {
    const zip = new JSZip();
    for (const [path, content] of Object.entries(files)) {
      zip.file(path, content);
    }
    const bytes = await zip.generateAsync({ type: 'uint8array', compression: 'DEFLATE' });
    outer.file(name, bytes, { compression: 'STORE', binary: true });
  }

  async function build(state, def) {
    const outer = new JSZip();

    outer.file('description.xml', descriptionXml(state));

    /* UI modules (nested zips) */
    for (const m of def.modules) {
      const entries = moduleEntries(state, def, m.value);
      if (!entries.length) continue;
      await nestedModule(outer, m.value, { 'theme_values.xml': themeValuesXml(entries) });
    }

    /* icons module */
    const iconFiles = Object.assign({ 'transform_config.xml': transformConfigXml(state) }, await iconAssets(state));
    await nestedModule(outer, 'icons', iconFiles);

    /* wallpapers — always present (uploaded image or configured gradient) */
    outer.file('wallpaper/default_wallpaper.jpg', await wallpaperBytes(state, 'homeWallpaper', 1080, 2340));
    outer.file('wallpaper/default_lock_wallpaper.jpg', await wallpaperBytes(state, 'lockWallpaper', 1080, 2340));

    /* store previews */
    outer.file('preview/preview_launcher_0.jpg', await previewImage(state, 'homeWallpaper', 'Home screen'));
    outer.file('preview/preview_lockscreen_0.jpg', await previewImage(state, 'lockWallpaper', 'Lock screen'));

    /* fonts */
    if (state.assets.fontRegular) {
      outer.file('fonts/Roboto-Regular.ttf', U.dataUrlToBytes(state.assets.fontRegular.dataUrl));
    }
    if (state.assets.fontBold) {
      outer.file('fonts/Roboto-Bold.ttf', U.dataUrlToBytes(state.assets.fontBold.dataUrl));
    }

    /* sounds */
    const sounds = [['ringtone', 'ringtone'], ['notifSound', 'notification'], ['alarmSound', 'alarm']];
    for (const [key, base] of sounds) {
      const a = state.assets[key];
      if (a) outer.file(`ringtones/${base}.${extOf(a.name, 'mp3')}`, U.dataUrlToBytes(a.dataUrl));
    }

    /* boot animation */
    if (state.assets.bootAnimation) {
      outer.file('boots/bootanimation.zip', U.dataUrlToBytes(state.assets.bootAnimation.dataUrl), { compression: 'STORE' });
    }

    return outer.generateAsync({ type: 'blob', mimeType: 'application/octet-stream', compression: 'DEFLATE' });
  }

  /* Text preview of every generated file for the "View files" modal. */
  function describe(state, def) {
    const files = [{ path: 'description.xml', content: descriptionXml(state) }];
    for (const m of def.modules) {
      const entries = moduleEntries(state, def, m.value);
      if (!entries.length) continue;
      files.push({ path: m.value + ' → theme_values.xml', content: themeValuesXml(entries) });
    }
    files.push({ path: 'icons → transform_config.xml', content: transformConfigXml(state) });

    const binaries = ['icons → icon_mask.png (generated)'];
    if (state.values.iconBgEnable) binaries.push('icons → icon_background.png (generated)');
    if (state.values.iconBorder) binaries.push('icons → icon_border.png (generated)');
    if (state.values.iconGloss) binaries.push('icons → icon_pattern.png (generated)');
    binaries.push(
      'wallpaper/default_wallpaper.jpg' + (state.assets.homeWallpaper ? '' : ' (generated gradient)'),
      'wallpaper/default_lock_wallpaper.jpg' + (state.assets.lockWallpaper ? '' : ' (generated gradient)'),
      'preview/preview_launcher_0.jpg (generated)',
      'preview/preview_lockscreen_0.jpg (generated)');
    if (state.assets.fontRegular) binaries.push('fonts/Roboto-Regular.ttf — ' + state.assets.fontRegular.name);
    if (state.assets.fontBold) binaries.push('fonts/Roboto-Bold.ttf — ' + state.assets.fontBold.name);
    for (const [key, base] of [['ringtone', 'ringtone'], ['notifSound', 'notification'], ['alarmSound', 'alarm']]) {
      const a = state.assets[key];
      if (a) binaries.push(`ringtones/${base}.${extOf(a.name, 'mp3')} — ${a.name}`);
    }
    if (state.assets.bootAnimation) binaries.push('boots/bootanimation.zip — ' + state.assets.bootAnimation.name);
    files.push({ path: 'Binary files', content: binaries.map(b => '• ' + b).join('\n') });

    return files;
  }

  window.MtzExport = { build, describe };
})();
